// src/services/authService.ts
import { supabase } from '../lib/supabase.js';
import { supabaseAdmin } from '../lib/supabaseAdmin.js';
import { aiParseTravelDocs } from './aiParseTravelDocs.js';
import { mapRowToUser } from '../utils/mapdb.js';

const authService = {
  async signUp(params: {
    email: string;
    password: string;
    firstName: string;
    lastName: string;
    phone?: string;
    imageBuffer?: Buffer;
    mimeType?: string;
  }) {
    // 1. Create user in Supabase Auth
    const { data: authData, error: authError } = await supabase.auth.signUp({
      email: params.email,
      password: params.password,
    });

    if (authError || !authData.user) {
      throw new Error(`Auth SignUp Error: ${authError?.message}`);
    }

    // Grab the ID generated by Supabase Auth
    const userId = authData.user.id;
    let travelDocUrl: string | null = null;
    let travelDocData: Record<string, any> = {};

    // 2. Upload photo & parse with Gemini Vision if provided
    if (params.imageBuffer && params.mimeType) {
      const fileExt = params.mimeType.split('/')[1] || 'jpg';
      const fileName = `${userId}/${Date.now()}.${fileExt}`;

      const { error: uploadError } = await supabaseAdmin.storage
        .from('travel-docs')
        .upload(fileName, params.imageBuffer, { contentType: params.mimeType });

      if (!uploadError) {
        const { data: publicUrl } = supabaseAdmin.storage
          .from('travel-docs')
          .getPublicUrl(fileName);
        
        travelDocUrl = publicUrl.publicUrl;
      }

      travelDocData = await aiParseTravelDocs(params.imageBuffer, params.mimeType);
    }

    // 3. Link profile into public.users table using authData.user.id.
    // Uses the service-role client: Supabase Auth signups don't establish a
    // session until email confirmation, so the anon client isn't authenticated
    // as the new user yet and RLS would reject this insert otherwise.
    const { data: inserted, error: dbError } = await supabaseAdmin
      .from('users')
      .insert({
        id: userId, // 👈 Uses Supabase Auth ID
        first_name: params.firstName,
        last_name: params.lastName,
        email: params.email,
        phone: params.phone || null,
        travel_doc_url: travelDocUrl,
        travel_doc_data: travelDocData,
      })
      .select()
      .single();

    if (dbError) throw new Error(`Database Insert Error: ${dbError.message}`);

    return {
      user: mapRowToUser(inserted),
      session: authData.session,
    };
  },

  /**
   * Uses Supabase Auth built-in authentication
   */
  async login(email: string, passwordAttempt: string) {
    const { data, error } = await supabase.auth.signInWithPassword({
      email,
      password: passwordAttempt,
    });

    if (error) throw new Error(`Login Error: ${error.message}`);

    // Fetch user profile from public.users
    const { data: userProfile } = await supabase
      .from('users')
      .select('*')
      .eq('id', data.user.id)
      .single();

    return {
      user: userProfile ? mapRowToUser(userProfile) : null,
      session: data.session,
    };
  },

  async logout() {
    const { error } = await supabase.auth.signOut();
    if (error) {
      throw new Error(`Logout Error: ${error.message}`);
    }
    return { success: true };
  }
};

export { authService };